apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-eventhub-processor
  labels:
    app: azure-eventhub-processor
    version: "1.0"
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: azure-eventhub-processor
  template:
    metadata:
      labels:
        app: azure-eventhub-processor
        version: "1.0"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      serviceAccountName: azure-eventhub-processor-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      containers:
        - name: azure-eventhub-processor
          image: your-registry/azure-eventhub-processor:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
            - name: EVENTHUBS_NAMESPACE
              valueFrom:
                secretKeyRef:
                  name: azure-credentials
                  key: eventhubs-namespace
            - name: EVENT_HUB_NAME
              value: "events"
            - name: CONSUMER_GROUP
              value: "processor-group"
            - name: STORAGE_ACCOUNT
              valueFrom:
                secretKeyRef:
                  name: azure-credentials
                  key: storage-account
            - name: STORAGE_CONTAINER
              value: "checkpoints"
            - name: DB_HOST
              value: "postgresql-service"
            - name: DB_NAME
              value: "eventprocessor"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: JVM_OPTS
              value: "-server -Xms2g -Xmx4g -XX:+UseG1GC -XX:MaxGCPauseMillis=200"

          resources:
            requests:
              memory: "2Gi"
              cpu: "1000m"
            limits:
              memory: "4Gi"
              cpu: "2000m"

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          volumeMounts:
            - name: config
              mountPath: /app/config
              readOnly: true

      volumes:
        - name: config
          configMap:
            name: azure-eventhub-processor-config

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: azure-eventhub-processor-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: azure-eventhub-processor
  minReplicas: 2
  maxReplicas: 16
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60